# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "vue"
        versions: ["3.x"]
      - dependency-name: "vue-template-compiler"
        versions: ["3.x"]
      - dependency-name: "vue-router"
        versions: ["4.x"]
      - dependency-name: "eslint-plugin-vue"
        versions: ["9.x"]
    allow:
      - dependency-name: "vue"
        versions: ["2.7.x"]
      - dependency-name: "vue-template-compiler"
        versions: ["2.7.x"]
      - dependency-name: "vue-router"
        versions: ["3.5.x"]
      - dependency-name: "eslint-plugin-vue"
        versions: ["6.2.x"]